version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-browsers
    steps:
      - checkout
      - run:
          name: Clone qxf2/cars-api repo
          command: |
            git clone https://github.com/qxf2/cars-api.git 
      - run:
          name: Install flask as it is needed to run our cars-api web server
          command: | 
            sudo pip install Flask
      - run:
          name: Run cars-app server in background as it is mandatory to run our API test
          command: | 
            python cars-api/cars_app.py
          background: true
      - run:
          name: Wait for sometime to start the server
          command: |
            sleep 5
      - run:
          name: Install requests
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Run the API and Selenium tests only (Ignoring to run mobile test as we are not yet set to run mobile test on server)
          command: |
            ls
            #pytest -s -v --ignore=./tests/test_mobile_bitcoin_price.py /tests/test_api_example.py --junitxml=test-reports/junit.xml --tb=native 
            #pytest -s -v tests/test_example_form.py --junitxml=test-reports/junit.xml --tb=native
            python tests/test_example_form.py
      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file